#!/usr/bin/python

# ID: REVC
# TITLE: Complementing a Strand of DNA

def reverse_and_complement(dna):
  complemented_reversed = ''
  strand = reversed(dna.upper())
  for i in strand:
    if i == 'A':
      complemented_reversed = complemented_reversed + 'T'
    elif i == 'T':
      complemented_reversed = complemented_reversed + 'A'
    elif i == 'C':
      complemented_reversed = complemented_reversed + 'G'
    elif i == 'G':
      complemented_reversed = complemented_reversed + 'C'
  return complemented_reversed
      
dna = '''GTTAGGCCAGATGGATGAGGCTGTGAAGTCCACTTCTCAAGTGTTAAGCTCC
      AGAGGTAAAGCAATGATTAAAACTAGGCGCACGCGAGCTCCCACATCAGCGTGTT
      CCAATGGTCGTACCGCAGTTGAGACTTTATAATCCGTCCGCATACAAAGTCGGAG
      GTTTTCTAGCAACGATGATCGAGTTGATAGCGAAGTGGATGGTTCATTCTCAATT
      GAAACCCCCCGGGTCATAGGTGCATAAGGGTAGAGGTTGCTACGCCGGTCTATTG
      CATAGTACATGCATGGCGGGATACGTTCTTCGATCGTATAAAAAGTGGATGAATC
      CCCACGAACCATACAAGATGTTTGCACGAGGCAGTCGGAGGGGGTTGGTATATCC
      TCATACTTGATCAGTGGCTTGGCCGAAAAACACAGAAGCAGAAGCCTTCTTACAA
      CGATACAGGACACAGATTGTCTCTTTGCATTGCCCGTGGAGTTGTGGTCTGAGCA
      GATTTGGCTGTACAACCTTATGTACTGCTTCAAGGCCATGCGGAGTTGCCATCAT
      TCAATTGTATATCATGGCGGACCAGTTATCCGGCATGGCTTGGTGGACAGCGGTA
      AAAAGAGACCTTCTGTAGCATTTCAAGATCAGAACCCACCGTTACCTGCCCTCAC
      AGTTTATGGCTCGACCACCGAACGAGTTAGGCATGTCGTTTAGGCCCCAGTGGGT
      TGTCCGACGATACCGCCTGGTGCTACTGACAGAGGACTAGGCCTACTGGAAAGGC
      CTAATGTGTTGCGTATCCTAGGCCCATTCGGCC'''

complement_reversed = reverse_and_complement(dna)
print complement_reversed
      