#!/usr/bin/python

# ID: RNA
# TITLE: Transcribing DNA into RNA

def transcribe(dna):
  dna = dna.upper()
  rna = ''
  for i in dna:
    if i == 'T':
      rna = rna + 'U'
    else:
      rna = rna + i
  return rna

dna = '''GGATGAGGCATAAGACATCCTACACGACCCTTAACTAGTCTAAAGC
      GCAGTGATGTGGAACGTCTCTTTACCACAAAGGCTCAAAGAAGCAACTT
      TTCCTCATCTGGCCAATTGTTGAACCGACGACACGCAAACTCATGGAGC
      TAGACGTTATAAGTGGTGTCAATCCTGCTTTAGGTAGGAACCAGCAATA
      TAAAACGAAACCCACAACATGATTTCCCCAGTACCACGAATAGCTACGG
      GTTAAGCACGTGGCAAACCCGAGCAGCAATGGCGACATCTATATCTGAA
      TGCCATGTCCGTCCCTGTACACCCTCAAGACGAACAGTCGTCTCATGCT
      TCAGTTAAAACGCGACCCACGCTGTCGTTCGCCCTCAATATAAGTATAA
      TCCCACTTCCGAATTTTGTGGCTATCTGACTAATGGATGCTCATTGCTC
      GCCCAAACAATTGCCACCTTGTACACGACGCTGAAGATGCCGAGTAGTA
      ACATCGAGTACACATTCAGCTTGCGTTGGTGTATAATTTTTCATTTTTC
      GAACCGGACTAGTTTTGAATTGGGGACTCGCCTGATCCCTTTTTCCGAG
      TAACATTGATGTAACGGGATGGAGCTTTTCAAAACTATTTGCCGTTCTA
      CCATCCGGATACGGCCCGTGGTTCGAATGAGGATCTGACTCTCCTCGAC
      ACTGCCTGGCGAATACGGACACAAGCCCCTATACAAGGCAAGTTTACTC
      ATTTACCAAATTAGTGGGTTGACAAATGACTTCTTTGTTAGTGAGACTT
      CTATCGCCTCACTCTGGCCAGGTATAGCACAGTAGCTCTTCTTTGGGGC
      GGAGGGCAGGCGTAAATCGGCAGGCATGCCCCCATTCTCCCACGAAGCT
      TTGATTGCCTTCGTCGGCTGGGAATGCTAGTACAGTGGCCGGCC'''

rna = transcribe(dna)
print rna